### PR TITLE
Switch from Release to MinSizeRel, to shrink packages.

### PR DESCRIPTION
**Pull request by directhex**
This reduces the packages we build by 15-20%

### CODE REVIEW

**Review by steveisok — APPROVED** [review]
Assuming this has no real impact on the runtimes we produce, why not?

**Comment by akoeplinger** [comment]
I wonder if we have checks for config==Release somewhere that would be affected. It might also affect objwriter: https://github.com/dotnet/llvm-project/pull/386

**Comment by akoeplinger** [comment]
And now that I look at it, is hardcoding `-DCMAKE_BUILD_TYPE=Release` intentional? It was added as part of https://github.com/dotnet/llvm-project/pull/142

**Comment by directhex** [comment]
Hardcoding Release was intentional. We don't want full Debug builds of LLVM, but we do want LLVM builds which link against the Debug version of VCRuntime, so we can link against debug versions of Mono.

I need to investigate why this breaks Windows, though.

**Comment by directhex** [comment]
Found it, it's _another_ case of "LLVM build system PDB handling is garbage"

**Comment by akoeplinger** [comment]
This also needs a fix: https://github.com/dotnet/llvm-project/blob/e08f119fe5b5cace97abf56f69ac25717437c9d9/llvm/tools/objwriter/CMakeLists.txt#L12

Since it uses `CMAKE_SHARED_LINKER_FLAGS_<CONFIG>` and we're changing the config.

Hopefully there are not more worms like this hiding somewhere ....

**Comment by directhex** [comment]
OK, build is green. Just needs validation that it isn't slower

**Comment by akoeplinger** [comment]
Closing this for now until someone has time to actually look at the impact of this.

**Pull request closed without merging**
