### PR TITLE
Bring proper fix for warnings about missing children

### PR DESCRIPTION
**Pull request by agocke**
My previous change in #363 did not correctly account for all the possible items that could create a child entry. This caused an extra null entry to be created, which was treated as the end of the section.

This change is more thorough and features NoChildren abbrev sections, which should hopefully be a little safer, as it will avoid having to produce extra null entries. I've done some extra validation on this change to make sure that roughly the same amount of DWARF info is produced in a test app before and after this change, so it's unlikely that we're truncating most of the info again.

### CODE REVIEW

**Comment by agocke** [comment]
@dotnet/jit-contrib for review

**Comment by agocke** [comment]
fyi @filipnavara took your suggestion in this PR to add new NoChildren entries.

**Comment by filipnavara** [comment]
LGTM

**Review by markples — APPROVED** [review]
just a few comments from trying to learn my way around here:

- I was surprised a bit by the lack of symmetry between the abbreviations/`DW_CHILDREN_{yes,no}` and the explicit (conditional) calls to `HasChildren`/`emitIntValue`.  However, it looks like that's inherent in how these abbreviations work in dwarf itself and therefore the way to go here.
- There are two places that do the `HasChildren`/`emitIntValue` check, and there are many other places that do a similar emit.  Some clearly have a different purpose such as
  ```
  void DwarfPrimitiveTypeInfo::DumpStrings(MCObjectStreamer *Streamer) {
  ...
    Streamer->emitBytes(StringRef(TD.Name));
    Streamer->emitIntValue(0, 1);
  ```
  but others are less obvious like
  ```
  void DwarfEnumTypeInfo::Dump(UserDefinedDwarfTypesBuilder *TypeBuilder, MCObjectStreamer *Streamer,
      MCSection *TypeSection, MCSection *StrSection) {
      ...
    for (auto &Enumerator : Records) {
      Enumerator.Dump(TypeBuilder, Streamer, TypeSection, StrSection);
    }

    // Terminate DIE
    Streamer->SwitchSection(TypeSection);
    Streamer->emitIntValue(0, 1);
  ```
  I see that these methods call a shared `DwarfInfo::Dump` helper.  Should they perhaps call another shared `DwarfInfo::Finish` method that does anything necessary to finish the record (might only be doing the HasChildren check for now)?

  Perhaps a less intrusive change would be to simply extract the `emitIntValue(0, 1)` (and HasChildren where appropriate) into self-documenting helper calls such as `emitEndChildren()`

To be clear, I'm not insisting on these ideas but am mainly curious, especially since it looks like this was difficult to get right the first time.

**Comment by agocke** [comment]
> I see that these methods call a shared DwarfInfo::Dump helper. Should they perhaps call another shared DwarfInfo::Finish method that does anything necessary to finish the record (might only be doing the HasChildren check for now)?

> Perhaps a less intrusive change would be to simply extract the emitIntValue(0, 1) (and HasChildren where appropriate) into self-documenting helper calls such as emitEndChildren()

Seems very reasonable to me. I'll take a look at doing that instead.

**Comment by agocke** [comment]
@markples I went with a simple refactoring for now. In the future it might be worth it to try to have more well-defined prologue/epilogue functions.

**Comment by markples** [comment]
LGTM

**Pull request merged**
