### PR TITLE
Change CI to build everything by default

### PR DESCRIPTION
**Pull request by agocke**
First problem was that the ObjWriter package wasn't even being built.

### CODE REVIEW

**Comment by agocke** [comment]
Never mind. I still think it isn't being built, but I'm not sure this fixes it.

**Comment by MichalStrehovsky** [comment]
> Never mind. I still think it isn't being built, but I'm not sure this fixes it.

It looked fine in the official build: https://dnceng.visualstudio.com/internal/_build/results?buildId=1860485&view=results

**Comment by MichalStrehovsky** [comment]
> > Never mind. I still think it isn't being built, but I'm not sure this fixes it.
> 
> It looked fine in the official build: https://dnceng.visualstudio.com/internal/_build/results?buildId=1860485&view=results

I've opened https://github.com/dotnet/runtime/pull/72159 to manually update runtime repo to the build from this official run just to see if the packages are okay.

**Comment by agocke** [comment]
Yeah, the problem was the branches, plus the fact that two branches publish to the same feed.

**Pull request closed without merging**
