### PR TITLE
Remove objwriter code from repo

### LINKED ISSUE #99782: For `dotnet/llvm-project` only: Remove ObjWriter cpp code.
It was mentioned that the LLVM ObjWriter native code is merged with `main` on [`dotnet/llvm-project`](https://github.com/dotnet/llvm-project). Now that we are no longer using LLVM ObjWriter (see https://github.com/dotnet/runtime/pull/99733), we should delete the ObjWriter native code from `main` in [`dotnet/llvm-project`.](https://github.com/dotnet/llvm-project)

### PR DESCRIPTION
**Pull request by akoeplinger**
Fixes https://github.com/dotnet/runtime/issues/99782

### CODE REVIEW

**Review by TIHan — APPROVED** [review]
This is great! Thank you for this!

**Comment by MichalStrehovsky** [comment]
We also had various patches to LLVM itself - will they be dropped next time we do a major LLVM upgrade? (Would be annoying for someone to resolve merge conflicts in these, if there's any - I don't know what is our LLVM major version upgrade strategy.)

**Comment by akoeplinger** [comment]
@MichalStrehovsky we usually apply our patches again when doing an LLVM upgrade. I guess we should revert https://github.com/dotnet/llvm-project/commit/67f5503adc0fe9d886a33df58f49a4b3e2b8c21e too then? are you aware of any other changes to llvm?

**Comment by MichalStrehovsky** [comment]
> @MichalStrehovsky we usually apply our patches again when doing an LLVM upgrade. I guess we should revert [67f5503](https://github.com/dotnet/llvm-project/commit/67f5503adc0fe9d886a33df58f49a4b3e2b8c21e) too then? are you aware of any other changes to llvm?

No other changes off the top of my head.

**Comment by akoeplinger** [comment]
Opened a PR to revert those changes: https://github.com/dotnet/llvm-project/pull/543

**Pull request merged**
