### PR TITLE
Upgrade LLVM to 16

### PR DESCRIPTION
**Pull request by directhex**
This PR updates our internal LLVM fork from 14 to 16.

One of the requirements of this is LLVM 16 depends on C++17, which is not available in our CBL Mariner target crossroots. To work around this, we need to build/ship/link against LLVM's C++ library, `libc++`, on Linux. ALL consumers which link against files produced from llvm-project.git need to switch to our build of libc++ instead of distro-provided `libstdc++` (from GCC).

We are using `rpath` to direct searches for `libc++` to `../lib/` which is a good match for the Mono consumers, but may be confusing for the CoreCLR consumers - we will need to see how this comes out in the wash.

LLVM 16 is a strict requirement for shipping self-build EMSDK, as we rely upon compiler flags which are in 16 but not 14. And from experience, we know trying to maintain multiple versions of LLVM within a single release is a huge maintenance burden.

### CODE REVIEW

**Comment by directhex** [comment]
Green except for ARM32 Windows, which is being removed in https://github.com/dotnet/llvm-project/pull/419

**Comment by SamMonoRT** [comment]
@jandupej @vargaz - have we done and local validation ?

**Comment by vargaz** [comment]
Comments:
- We use to maintain our branches by rebasing our changes on top of the llvm release branches, are we going to stop doing that ?
- emscripten is probably tested with a fixed llvm version which might not be the one our fork is based on, so it might not actually work.

**Comment by directhex** [comment]
> * emscripten is probably tested with a fixed llvm version which might not be the one our fork is based on, so it might not actually work.

Emscripten does the literal opposite of that. It checks out LLVM git main and builds with that. Building the 3.1.34 tag today will give you a completely different emscripten than building 3.1.34 tag a week ago, which gives you a completely different result from when 3.1.34 was tagged. There is nothing resembling "fixed" in the emsdk build system.

**Comment by directhex** [comment]
> We use to maintain our branches by rebasing our changes on top of the llvm release branches, are we going to stop doing that ?

That's doable too.

**Comment by directhex** [comment]
Closing for now, we have the dotnet/main-16.x merge done & will keep working in there for now

**Pull request closed without merging**
