### PR TITLE
native FreeBSD build support

### PR DESCRIPTION
**Pull request by Thefrank**
Adds support for building ObjWriter, JITTools, and LLVM items natively under FreeBSD using `BuildOS`

### CODE REVIEW

**Comment by Thefrank** [comment]
Some notes:
- This still requires users of the package(s) to manually add the missing items to https://github.com/dotnet/runtime/blob/main/eng/Versions.props
- FreeBSD maintains a "ports" version of the upstream llvm-project with some additional patches (see: https://github.com/freebsd/freebsd-ports/tree/main/devel/llvm16/files) these mostly cover using the repo with FreeBSD's ports system, PPC support, and ARM build issues.
- This repo does not appear to build the tests for this, but all of the output produces correct FreeBSD ELFs and the ObjWriter has been used in FreeBSD builds for runtime without issue.
- When I get more time I can add back the crossbuild support I used from the 14-based branch; likely in a different PR.

**Comment by Thefrank** [comment]
Not sure why the muslx64 failed. The error seems to indicate a missing cmake target needed by a dependency.

**Review by akoeplinger — APPROVED** [review]

**Comment by akoeplinger** [comment]
> Not sure why the muslx64 failed. The error seems to indicate a missing cmake target needed by a dependency.

Looks like an unrelated issue to me, I've retried the build.

**Comment by akoeplinger** [comment]
Thank you!

**Pull request merged**
