### PR TITLE
Upgrade macos image to 11

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
10.15 got deprecated.

### CODE REVIEW

**Comment by am11** [comment]
Already covered it in #185. Can you please merge that PR?

**Comment by MichalStrehovsky** [comment]
> Already covered it in https://github.com/dotnet/llvm-project/pull/185. Can you please merge that PR?

The CI in this repo is just a build - it doesn't test anything. I want to get an objwriter package out that we can test in the runtime repo. The official build with Filip's change failed because of the brownout.

I don't want to conflate #269 with your PR because if we hit a snag in the runtime repo I won't know which PR to blame.

**Comment by am11** [comment]
> I don't want to conflate https://github.com/dotnet/llvm-project/pull/269 with your PR because if we hit a snag in the runtime repo I won't know which PR to blame.

Sure. But it is not possible to use objwriter on osx-arm64 with https://github.com/dotnet/llvm-project/pull/269, without https://github.com/dotnet/llvm-project/pull/185. It is possible the other way around. ;)

**Comment by MichalStrehovsky** [comment]
> Sure. But it is not possible to use objwriter on osx-arm64 with https://github.com/dotnet/llvm-project/pull/269, without https://github.com/dotnet/llvm-project/pull/185. It is possible the other way around. ;)

Right, but it's possible to _break_ non-osx-arm64 platforms with either of the PRs :)

**Pull request merged**
